[tool.poetry]
name = "api"
version = "0.1.0"
description = ""
authors = ["cording12 <joncording12@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.115.0"
uvicorn = "^0.34.0"
email-validator = "^2.3.0"
pydantic-settings = "^2.7.0"
python-dotenv = "^1.2.1"
supabase = "^2.15.0"
python-socketio = {version = "^5.16.0", extras = ["asgi"]}

[tool.poetry.group.dev.dependencies]
isort = "^5.13.2"
black = "^24.10.0"
pytest = "^8.4.2"
pylint-pydantic = "^0.4.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
